# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiLike' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HiLike


  target 'HiLikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HiLike-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HiLike-tvOS

  target 'HiLike-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
